# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://khasang.github.io/SmartForecast/
title: Smart Forecast
email: smartforecast@khasang.org
author: Khasang
description: > # "Write an awesome description for your new site here. 
  You can edit this line in _config.yml. It will appear in your document 
  head meta (for Google search results) and in your feed.xml site 
  description.
copyright: 'Copyright &copy; 2016 Smart Forecast. All Rights Reserved.'

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: android
    txt: Google Play
    url: https://play.google.com/store/apps/details?id=com.khasang.forecast
  - title: github
    txt: GitHub
    url: https://github.com/khasang/SmartForecast
  - title: vk
    txt: VK
    url: http://vk.com/smartforecast
